name: Deploy to Remote Server

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: 
          echo "HAS_PASSWORD=${{ secrets.RASPBERRY_PI_PASSWORD != '' }}" >> $GITHUB_ENV
      - name: Copy code to remote server
        run: |
          sshpass -p ${{ secrets.RASPBERRY_PI_PASSWORD }} scp -P 2048 -o StrictHostKeyChecking=no -r . lucas-rasp@62.34.161.92:/home/lucas-rasp/Console/.
        if: env.HAS_PASSWORD
      - name: Run script on remote server
        run: 
          sshpass -p ${{ secrets.RASPBERRY_PI_PASSWORD }} ssh -o StrictHostKeyChecking=no lucas-rasp@62.34.161.92 -p 2048 'cd /home/lucas-rasp/Console && tmux send-keys -d Console "mvn spring-boot:run" C-m'
        if: env.HAS_PASSWORD
