# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  push-to-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      run: mvn -B compile
    - name: Tests
      run: mvn -B test
    - name: Edit Version to Latests
      run: mvn -B versions:set -DnewVersion="latest"
    - name: Authent to Github Docker Registry
      run: docker login -u Skytowz -p ${{ secrets.DOCKER_TOKEN }} ghcr.io
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B spring-boot:build-image -Denv.CI_PROJECT="hayasaku.console" -DskipTests -Denv.CI_REGISTRY="ghcr.io"
